# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "Babel" = super.buildPythonPackage rec {
    pname = "Babel";
    version = "2.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/15/a1/522dccd23e5d2e47aed4b6a16795b8213e3272c7506e625f2425ad025a19/Babel-2.8.0-py2.py3-none-any.whl";
      sha256 = "1m2jq6g2crhvp96npmr0l96j8nsngfwbwsis5mkj7dzq205ylw6n";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pytz"
    ];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "MarkupSafe" = super.buildPythonPackage rec {
    pname = "MarkupSafe";
    version = "1.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b9/2e/64db92e53b86efccfaea71321f597fa2e1b2bd3853d8ce658568f7a13094/MarkupSafe-1.1.1.tar.gz";
      sha256 = "0sqipg4fk7xbixqd8kq6rlkxj664d157bdwbh93farcphf92x1r9";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.bsd3 pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "amqp" = super.buildPythonPackage rec {
    pname = "amqp";
    version = "2.5.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fc/a0/6aa2a7923d4e82dda23db27711d565f0c4abf1570859f168e3d0975f1eb6/amqp-2.5.2-py2.py3-none-any.whl";
      sha256 = "1f7k9wgklmvy0wv56m4xzli2sq56m452ifwbvjngmwvx7ahrqr3f";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."vine"
    ];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "apscheduler" = super.buildPythonPackage rec {
    pname = "apscheduler";
    version = "3.6.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f3/34/9ef20ed473c4fd2c3df54ef77a27ae3fc7500b16b192add4720cab8b2c09/APScheduler-3.6.3-py2.py3-none-any.whl";
      sha256 = "09p5c8if0rm9sfj101v86s4wpiw3h64xarpp2f4q3ckw9kdyrcg8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pytz"
      self."setuptools"
      self."six"
      self."tzlocal"
    ];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "argparse" = super.buildPythonPackage rec {
    pname = "argparse";
    version = "1.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl";
      sha256 = "0533cr5w14da8wdb2q4py6aizvbvsdbk3sj7m1jx9lwznvnlf5n3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.psfl ];
    };
  };
  "bcrypt" = super.buildPythonPackage rec {
    pname = "bcrypt";
    version = "3.1.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fa/aa/025a3ab62469b5167bc397837c9ffc486c42a97ef12ceaa6699d8f5a5416/bcrypt-3.1.7.tar.gz";
      sha256 = "0hhywhxx301cxivgxrpslrangbfpccc8y83qbwn1f57cab3nj00b";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      self."setuptools"
      self."wheel"
      self."cffi"
    ];
    propagatedBuildInputs = [
      self."cffi"
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2020.4.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/57/2b/26e37a4b034800c960a00c4e1b3d9ca5d7014e983e6e729e33ea2f36426c/certifi-2020.4.5.1-py2.py3-none-any.whl";
      sha256 = "016kmf145apmfkrpxwd7434hcjchypy6djbwhi03qqvmijcpm60x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mpl20 { fullName = "Mozilla Public License 2.0 (MPL 2.0)"; } ];
    };
  };
  "cffi" = super.buildPythonPackage rec {
    pname = "cffi";
    version = "1.14.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/54/3324b0c46340c31b909fcec598696aaec7ddc8c18a63f2db352562d3354c/cffi-1.14.0.tar.gz";
      sha256 = "1dn279gw5ql8i5n3s5v4rnv96rhhjjfn7xq729qbl5bs2954yf1d";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pycparser"
    ];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "chardet" = super.buildPythonPackage rec {
    pname = "chardet";
    version = "3.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl";
      sha256 = "14b621614q2lw7ik2igdv4qdbblqgdsiglgl5fhf1l5fmvy3ycpw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ { fullName = "LGPL"; } { fullName = "GNU Library or Lesser General Public License (LGPL)"; } ];
    };
  };
  "click" = super.buildPythonPackage rec {
    pname = "click";
    version = "7.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/dd/c0/4d8f43a9b16e289f36478422031b8a63b54b6ac3b1ba605d602f10dd54d6/click-7.1.1-py2.py3-none-any.whl";
      sha256 = "16hv8y5lq7wl4zkirfvbf4i5xshjw7jn8q856isyxx8bv11x2ig3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.bsd3 pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "cryptography" = super.buildPythonPackage rec {
    pname = "cryptography";
    version = "2.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/be/60/da377e1bed002716fb2d5d1d1cab720f298cb33ecff7bf7adea72788e4e4/cryptography-2.8.tar.gz";
      sha256 = "0l8nhw14npknncxdnp7n4hpmjyscly6g7fbivyxkjwvlv071zniw";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cffi"
      self."six"
    ];
    meta = {
      license = [ { fullName = "BSD or Apache License, Version 2.0"; } pkgs.lib.licenses.bsdOriginal pkgs.lib.licenses.asl20 ];
    };
  };
  "debtcollector" = super.buildPythonPackage rec {
    pname = "debtcollector";
    version = "2.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d0/9e/d3c893e756fa4901f6851bd1cc625629c1f57804ebce6726884aa1efa5e0/debtcollector-2.0.1-py3-none-any.whl";
      sha256 = "0bb0ii0kdikad8sp69yaar07k2jbzzhp5nwqj6622xyyndyykgcn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pbr"
      self."six"
      self."wrapt"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "decorator" = super.buildPythonPackage rec {
    pname = "decorator";
    version = "4.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl";
      sha256 = "0q7p11gj5g158gb1igy9cna5ppxf03zkrm2gpr4acjycl3159yj1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ { fullName = "new BSD License"; } pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "dnspython" = super.buildPythonPackage rec {
    pname = "dnspython";
    version = "1.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/d3/3aa0e7213ef72b8585747aa0e271a9523e713813b9a20177ebe1e939deb0/dnspython-1.16.0-py2.py3-none-any.whl";
      sha256 = "0bb3y7j6wdly1pl41myk71wvl6ni95dr1i2ndsl4sbwni8l2377n";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ { fullName = "BSD-like"; } { fullName = "Freeware"; } ];
    };
  };
  "eventlet" = super.buildPythonPackage rec {
    pname = "eventlet";
    version = "0.25.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ef/01/83454d11bac9015f34e93cf11efcae169390ddf2df97cb73ca86de6465ed/eventlet-0.25.1-py2.py3-none-any.whl";
      sha256 = "1cg6plbj43pw0175r23jlqn4xxi80lg89qhdhsjc3b9p17c1r2v5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."dnspython"
      self."greenlet"
      self."monotonic"
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "fasteners" = super.buildPythonPackage rec {
    pname = "fasteners";
    version = "0.15";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/18/bd/55eb2d6397b9c0e263af9d091ebdb756b15756029b3cededf6461481bc63/fasteners-0.15-py2.py3-none-any.whl";
      sha256 = "0x354b317l1ax5b42wkp7fwfmli2cwbfacp9cwzhj42a5lmlszh0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."monotonic"
      self."six"
    ];
    meta = {
      license = [ { fullName = "ASL 2.0"; } pkgs.lib.licenses.asl20 ];
    };
  };
  "flex" = super.buildPythonPackage rec {
    pname = "flex";
    version = "6.14.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2f/98/5baabcb05fe0f308e8cabf2015581cf1711e230a6824ab74d6038326a036/flex-6.14.0-py3-none-any.whl";
      sha256 = "1x8fra11wvrqlvlldl1s4mbrr05prl7vkw2b7qv2ji19a5lsq5rj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."click"
      self."jsonpointer"
      self."pyyaml"
      self."requests"
      self."rfc3987"
      self."six"
      self."strict-rfc3339"
      self."validate-email"
    ];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "futurist" = super.buildPythonPackage rec {
    pname = "futurist";
    version = "2.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/be/d0/937ba547a5a3aeab8b55c903671cf55814fa945c7a9b308179c2b1fb779a/futurist-2.1.1-py3-none-any.whl";
      sha256 = "1yrlyq4ljk4shc51wmkw8wj4zcp6kd5x21b95rcsllircby0hiw9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pbr"
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "gitdb2" = super.buildPythonPackage rec {
    pname = "gitdb2";
    version = "2.0.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/03/6c/99296f89bad2ef85626e1df9f677acbee8885bb043ad82ad3ed4746d2325/gitdb2-2.0.6-py2.py3-none-any.whl";
      sha256 = "0ywb5262i1sfkzcf0wpph92ifjhrzsf4lm82p0ggb9v5sw3vbfwn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."smmap2"
    ];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "gitpython" = super.buildPythonPackage rec {
    pname = "gitpython";
    version = "2.1.15";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7a/c9/6e1aec0893efe66f407d2e14a3daba73dbb39bbeeb72142b037c4a224d40/GitPython-2.1.15-py2.py3-none-any.whl";
      sha256 = "1xsl3qpbbl86f8r6hih335qf98vaw42avkh12dq685gwqncxxd13";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."gitdb2"
    ];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "greenlet" = super.buildPythonPackage rec {
    pname = "greenlet";
    version = "0.4.15";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f8/e8/b30ae23b45f69aa3f024b46064c0ac8e5fcb4f22ace0dca8d6f9c8bbe5e7/greenlet-0.4.15.tar.gz";
      sha256 = "1g4g1wwc472ds89zmqlpyan3fbnzpa8qm48z3z1y6mlk44z485ll";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "2.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl";
      sha256 = "1yk5hf2jkw1237b508mxmcdm8zqhfh26fr6rpwyxd968x8fa4s50";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ { fullName = "BSD-like"; } pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "importlib-metadata" = super.buildPythonPackage rec {
    pname = "importlib-metadata";
    version = "1.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ad/e4/891bfcaf868ccabc619942f27940c77a8a4b45fd8367098955bb7e152fb1/importlib_metadata-1.6.0-py2.py3-none-any.whl";
      sha256 = "03yr2r83p7m0fvwv6py3v7fcrbbfgb4vsj6zy63wa30fm6x8qs1a";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."zipp"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "ipaddr" = super.buildPythonPackage rec {
    pname = "ipaddr";
    version = "2.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9d/a7/1b39a16cb90dfe491f57e1cab3103a15d4e8dd9a150872744f531b1106c1/ipaddr-2.2.0.tar.gz";
      sha256 = "1ml8r8z3f0mnn381qs1snbffa920i9ycp6mm2am1d3aqczkdz4j0";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "iso8601" = super.buildPythonPackage rec {
    pname = "iso8601";
    version = "0.1.12";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ef/57/7162609dab394d38bbc7077b7ba0a6f10fb09d8b7701ea56fa1edc0c4345/iso8601-0.1.12-py2.py3-none-any.whl";
      sha256 = "18w93if6rxhbyc5xpq9f6xnxgqgi3pp7y218c0px1h3wcws023i1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "jinja2" = super.buildPythonPackage rec {
    pname = "jinja2";
    version = "2.10.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/65/e0/eb35e762802015cab1ccee04e8a277b03f1d8e53da3ec3106882ec42558b/Jinja2-2.10.3-py2.py3-none-any.whl";
      sha256 = "07winlq4s5mk8azs9x0rsv1q0spl7bij4rfla6ahy9ri3ywhnckl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."MarkupSafe"
    ];
    meta = {
      license = [ pkgs.lib.licenses.bsd3 pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "jsonpath-rw" = super.buildPythonPackage rec {
    pname = "jsonpath-rw";
    version = "1.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/71/7c/45001b1f19af8c4478489fbae4fc657b21c4c669d7a5a036a86882581d85/jsonpath-rw-1.4.0.tar.gz";
      sha256 = "1v7vqkx136y8xm2xx05ajqp1m0x4qy72dl83c4zi3bj53hl73i05";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."decorator"
      self."ply"
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "jsonpointer" = super.buildPythonPackage rec {
    pname = "jsonpointer";
    version = "2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/18/b0/a80d29577c08eea401659254dfaed87f1af45272899e1812d7e01b679bc5/jsonpointer-2.0-py2.py3-none-any.whl";
      sha256 = "07hw6symim5jqbfgjqqlcyjv3gj5fxy4dv7m76simf6i46h9ydzz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal { fullName = "Modified BSD License"; } ];
    };
  };
  "jsonschema" = super.buildPythonPackage rec {
    pname = "jsonschema";
    version = "2.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl";
      sha256 = "024sfr3bjikmsf085ignkdgi5lg7rah2ajal9192m5rwsfmnh3h0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "kazoo" = super.buildPythonPackage rec {
    pname = "kazoo";
    version = "2.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e8/99/3fae8ced30d6342e8001a51d4715c540ce01df6436543fc72bc8b8b8c71c/kazoo-2.7.0-py2.py3-none-any.whl";
      sha256 = "1dnnfpxnb2x0g3qn1lbjrvdjjc86z5qn2bwfymqlkfxk4v8zz0zg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "kombu" = super.buildPythonPackage rec {
    pname = "kombu";
    version = "4.6.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f7/86/496db94e44c6d0a16a52a1b539b5315d98e8aa59d14a8d4f1009d4eab6c2/kombu-4.6.6-py2.py3-none-any.whl";
      sha256 = "0w8py12z62p9lpfdq91k23xd484mw9fqrw0rd08qkf0xbal5lip7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."amqp"
      self."importlib-metadata"
    ];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "lockfile" = super.buildPythonPackage rec {
    pname = "lockfile";
    version = "0.12.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c8/22/9460e311f340cb62d26a38c419b1381b8593b0bb6b5d1f056938b086d362/lockfile-0.12.2-py2.py3-none-any.whl";
      sha256 = "1yjhkm1cg3i5ay3b0wb13fnag3ic31ssvmc54w5x68s96i7v4g3c";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "mongoengine" = super.buildPythonPackage rec {
    pname = "mongoengine";
    version = "0.18.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a7/1c/0749992c7a2b6a2f1879ad44ba5285f907d2024838459b4cd635c5e5effd/mongoengine-0.18.2.tar.gz";
      sha256 = "1xx2whg352ycy0p132q20np7mjmwam7sq0qirhabi8pwcv4p6gps";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pymongo"
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "monotonic" = super.buildPythonPackage rec {
    pname = "monotonic";
    version = "1.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ac/aa/063eca6a416f397bd99552c534c6d11d57f58f2e94c14780f3bbf818c4cf/monotonic-1.5-py2.py3-none-any.whl";
      sha256 = "1iqc2k8nmk6bkqisg3xvca4hh20rl9ajcskws35k6bjkh7rr2ajm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ { fullName = "Apache"; } pkgs.lib.licenses.asl20 ];
    };
  };
  "msgpack" = super.buildPythonPackage rec {
    pname = "msgpack";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e4/4f/057549afbd12fdd5d9aae9df19a6773a3d91988afe7be45b277e8cee2f4d/msgpack-1.0.0.tar.gz";
      sha256 = "1h5mxh84rcw04dvxy1qbfn2hisavfqgilh9k09rgyjhd936dad4m";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "netaddr" = super.buildPythonPackage rec {
    pname = "netaddr";
    version = "0.7.19";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ba/97/ce14451a9fd7bdb5a397abf99b24a1a6bb7a1a440b019bebd2e9a0dbec74/netaddr-0.7.19-py2.py3-none-any.whl";
      sha256 = "1jh87s49dz1xywsk7559m2km83k672gk8bn5wjcnjgqzsy5mbcsn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "netifaces" = super.buildPythonPackage rec {
    pname = "netifaces";
    version = "0.10.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0d/18/fd6e9c71a35b67a73160ec80a49da63d1eed2d2055054cc2995714949132/netifaces-0.10.9.tar.gz";
      sha256 = "1wxby874kcr3pp4ygzk5aiarbzhg1yi093d56s1qg4k2s7yrzvid";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "networkx" = super.buildPythonPackage rec {
    pname = "networkx";
    version = "1.11";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d3/2c/e473e54afc9fae58dfa97066ef6709a7e35a1dd1c28c5a3842989322be00/networkx-1.11-py2.py3-none-any.whl";
      sha256 = "1zy12ngnn8dbmls5sz9aaix4k491an42mq2dxsf01jwwzra9n8hv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."decorator"
    ];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "orquesta" = super.buildPythonPackage rec {
    pname = "orquesta";
    version = "1.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/82/d6e068ecb386fdbbe83c2051262f518dd4443eefa92d6f5fc8baa779a46b/orquesta-1.1.1-py3-none-any.whl";
      sha256 = "1xjh24p5vgr46d89jk643spsh1mkz7mpv3p2w0f6sm0qcbw25197";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."chardet"
      self."eventlet"
      self."jinja2"
      self."jsonschema"
      self."networkx"
      self."python-dateutil"
      self."pyyaml"
      self."six"
      self."stevedore"
      self."ujson"
      self."yaql"
    ];
    meta = {
      license = [ { fullName = "Apache License (2.0)"; } pkgs.lib.licenses.asl20 ];
    };
  };
  "oslo.config" = super.buildPythonPackage rec {
    pname = "oslo.config";
    version = "1.12.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c7/82/263fa79866098034917be0def7ab4979480e6f429732cd6cd9f4e0405ec5/oslo.config-1.12.1-py2.py3-none-any.whl";
      sha256 = "0jypai43x8ygjf8xlcwh39gqmr8cpbmh97q110102pcmrq8isl6l";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."argparse"
      self."netaddr"
      self."six"
      self."stevedore"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "oslo.i18n" = super.buildPythonPackage rec {
    pname = "oslo.i18n";
    version = "4.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d1/59/16e07470ba39f9a18d679755d66452acd36ca3e03e98aa109f3ff7def649/oslo.i18n-4.0.1-py3-none-any.whl";
      sha256 = "0wgygmrxq7kn3rmn537z0i9c03ayc414bln0040qkm991d1pndgc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Babel"
      self."pbr"
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "oslo.serialization" = super.buildPythonPackage rec {
    pname = "oslo.serialization";
    version = "3.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1e/95/7b2911102a78df16bb6feb1267821608da9f422375b86466cfc75a6ad4c9/oslo.serialization-3.1.1-py3-none-any.whl";
      sha256 = "0dxmrshqs1j9iiprxq6qmcipw6lpi081f9djwz9krh6yi9la936y";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."debtcollector"
      self."msgpack"
      self."oslo.utils"
      self."pbr"
      self."pytz"
      self."pyyaml"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "oslo.utils" = super.buildPythonPackage rec {
    pname = "oslo.utils";
    version = "4.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a6/4b/a589adaf957c89818102a19c800ae04fb3d6f4c7eaf670b23cd3c8e4f3c5/oslo.utils-4.1.1-py3-none-any.whl";
      sha256 = "0azrzr0l97a7j9f9462bha2dll46cbmxwvh5lk1wc1006zsvjgzx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."debtcollector"
      self."iso8601"
      self."netaddr"
      self."netifaces"
      self."oslo.i18n"
      self."pbr"
      self."pyparsing"
      self."pytz"
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "paramiko" = super.buildPythonPackage rec {
    pname = "paramiko";
    version = "2.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/1e/1e08baaaf6c3d3df1459fd85f0e7d2d6aa916f33958f151ee1ecc9800971/paramiko-2.7.1-py2.py3-none-any.whl";
      sha256 = "0bvvm4af37srk4dxpr2v7xj9d47ns2ifjr26c18vfb2dz9shi64w";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."bcrypt"
      self."cryptography"
      self."pynacl"
    ];
    meta = {
      license = [ { fullName = "LGPL"; } { fullName = "GNU Library or Lesser General Public License (LGPL)"; } ];
    };
  };
  "pbr" = super.buildPythonPackage rec {
    pname = "pbr";
    version = "5.4.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/96/ba/aa953a11ec014b23df057ecdbc922fdb40ca8463466b1193f3367d2711a6/pbr-5.4.5-py2.py3-none-any.whl";
      sha256 = "1s13pashfg3bmqach8hkzdwwpv28yrqjyqfyn0j2y34f7zi714ap";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "ply" = super.buildPythonPackage rec {
    pname = "ply";
    version = "3.11";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl";
      sha256 = "1kh7m0i2ghjhrbzi6a28yw3rcnzy5r2i4srls4pvspmna21rnvq9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "pyOpenSSL" = super.buildPythonPackage rec {
    pname = "pyOpenSSL";
    version = "19.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/de/f8342b68fa9e981d348039954657bdf681b2ab93de27443be51865ffa310/pyOpenSSL-19.1.0-py2.py3-none-any.whl";
      sha256 = "011m0q162n8xw4nasw191sq6m5ki43m58bqv5z78w2vjbab80632";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cryptography"
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "pycparser" = super.buildPythonPackage rec {
    pname = "pycparser";
    version = "2.20";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl";
      sha256 = "01apwc8fj6qh7lr01yxmns475rfhz07gccr8220ws3wgcwiav0km";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "pymongo" = super.buildPythonPackage rec {
    pname = "pymongo";
    version = "3.10.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5d/86/bfcec2a1c99e52344530e581a89871738bdcbf2c8f2ba681ad891e0980f1/pymongo-3.10.0.tar.gz";
      sha256 = "0z1h7yzh9h1cxq7zw4z6ryj2hi51bbfgpsfshipam9ky8bz7jf64";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "pynacl" = super.buildPythonPackage rec {
    pname = "pynacl";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/61/ab/2ac6dea8489fa713e2b4c6c5b549cc962dd4a842b5998d9e80cf8440b7cd/PyNaCl-1.3.0.tar.gz";
      sha256 = "0330wyvggm19xhmwmz9rrr97lzbv3siwfy50gmax3vvgs7nh0q8c";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      self."setuptools"
      self."wheel"
      self."cffi"
    ];
    propagatedBuildInputs = [
      self."cffi"
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "pyparsing" = super.buildPythonPackage rec {
    pname = "pyparsing";
    version = "2.4.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl";
      sha256 = "12y8xwjb118a4jqvvfg9k90kqg03n4d3ygb5csz0l81wxy4pb7gg";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "python-dateutil" = super.buildPythonPackage rec {
    pname = "python-dateutil";
    version = "2.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl";
      sha256 = "1yzj7m4h5babisvqac674xx82a8gd7ynxqhm2rwj7mpf9b3q8rby";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
    meta = {
      license = [ { fullName = "Dual License"; } pkgs.lib.licenses.bsdOriginal pkgs.lib.licenses.asl20 ];
    };
  };
  "python-statsd" = super.buildPythonPackage rec {
    pname = "python-statsd";
    version = "2.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6f/af/224e67da2deda72317aa9afe3445cf849ebd86f4001e20b5d164ef9d05f8/python_statsd-2.1.0-py2.py3-none-any.whl";
      sha256 = "107v0nd1iwbgx852km8j4xnwdggy9549w1nf1qxllivx78rv7f7h";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "pytz" = super.buildPythonPackage rec {
    pname = "pytz";
    version = "2019.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl";
      sha256 = "03ah44yp8013w30r69mylqnnal15zdh3z0ymrksy27c71rypsm8w";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "pyyaml" = super.buildPythonPackage rec {
    pname = "pyyaml";
    version = "5.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz";
      sha256 = "1r5faspz73477hlbjgilw05xsms0glmsa371yqdd26znqsvg1b81";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "repoze.lru" = super.buildPythonPackage rec {
    pname = "repoze.lru";
    version = "0.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b0/30/6cc0c95f0b59ad4b3b9163bff7cdcf793cc96fac64cf398ff26271f5cf5e/repoze.lru-0.7-py3-none-any.whl";
      sha256 = "1sk219iwh2qmcwz16jk0zqgamwngqmwk8pykmnz4b93f17hz0yzp";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ { fullName = "BSD-derived (http://www.repoze.org/LICENSE.txt)"; } { fullName = "Repoze Public License"; } ];
    };
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.23.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl";
      sha256 = "1vizszbz6mdn0fmb1i75d0n5w3jn5f4f968xmyv08ad8pwv916a3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."chardet"
      self."cryptography"
      self."idna"
      self."pyOpenSSL"
      self."urllib3"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "retrying" = super.buildPythonPackage rec {
    pname = "retrying";
    version = "1.3.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/44/ef/beae4b4ef80902f22e3af073397f079c96969c69b2c7d52a57ea9ae61c9d/retrying-1.3.3.tar.gz";
      sha256 = "0fwp86xv0rvkncjdvy2mwcvbglw4w9k0fva25i7zx8kd19b3kh08";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "rfc3987" = super.buildPythonPackage rec {
    pname = "rfc3987";
    version = "1.3.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/65/d4/f7407c3d15d5ac779c3dd34fbbc6ea2090f77bd7dd12f207ccf881551208/rfc3987-1.3.8-py2.py3-none-any.whl";
      sha256 = "0lyf5pysj3hv249nywgz9k7x4rh3bhc9n60b8r1qhrg5a4g2nw0h";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ { fullName = "GNU General Public License v3 or later (GPLv3+)"; } { fullName = "GNU GPLv3+"; } ];
    };
  };
  "routes" = super.buildPythonPackage rec {
    pname = "routes";
    version = "2.4.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/50/50/c1c0666778c7986368896b0e0f640e41160a43cd3ffc7ff008f61f0f6cfd/Routes-2.4.1-py2.py3-none-any.whl";
      sha256 = "0dg11p99b2i671g1j871l3fy1jfgwjind4pxda2ps4pg5gi8ljyn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."repoze.lru"
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "semver" = super.buildPythonPackage rec {
    pname = "semver";
    version = "2.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/38/f1/0c9b852c5136364c0dd59ee1d89e0d7599bef6c9f1869e0f2e07882253ea/semver-2.9.0-py2.py3-none-any.whl";
      sha256 = "0803fwnapzkw0dkg0k20dgyy19rmfzl7x6jh1kh4dqr3pzinn75a";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.13.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl";
      sha256 = "1zckxq1k0yyy65hzm3hmlvmiqhpvibkfm797nsfjl22lw917s6qz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "smmap" = super.buildPythonPackage rec {
    pname = "smmap";
    version = "3.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/27/b1/e379cfb7c07bbf8faee29c4a1a2469dbea525f047c2b454c4afdefa20a30/smmap-3.0.2-py2.py3-none-any.whl";
      sha256 = "1hgbigni2k6qdsz2cp1l2fwkvigfzg1nyfz9ryqc5lh8wyrpisjj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "smmap2" = super.buildPythonPackage rec {
    pname = "smmap2";
    version = "3.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3e/11/2dae3df2f19c43e156cce8e02c0080b46821faf816b839a2023ef7b6b84f/smmap2-3.0.1-py3-none-any.whl";
      sha256 = "095m5f4s5z0wlln82hsas9yiz1h1wrx4qzya09dadn8s1d3ymdhc";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."smmap"
    ];
    meta = {
      license = [  ];
    };
  };
  "st2common" = super.buildPythonPackage rec {
    pname = "st2common";
    version = "3.2.dev0";
    src = "${fetchgit {
        url = "https://github.com/stackstorm/st2.git";
        rev = "5bd298ac3ded9cad4eda0886b4d3197753edd0d3";
        sha256 = "0gl3pzh082d5hyacyqd6q63lwzvj97p7g4wlckdc8wvfjpchlfwq";
      }
    }/st2common";
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."amqp"
      self."apscheduler"
      self."cryptography"
      self."eventlet"
      self."flex"
      self."gitpython"
      self."greenlet"
      self."ipaddr"
      self."jinja2"
      self."jsonpath-rw"
      self."jsonschema"
      self."kombu"
      self."lockfile"
      self."mongoengine"
      self."networkx"
      self."orquesta"
      self."oslo.config"
      self."paramiko"
      self."pymongo"
      self."python-dateutil"
      self."python-statsd"
      self."pyyaml"
      self."requests"
      self."retrying"
      self."routes"
      self."semver"
      self."six"
      self."tooz"
      self."ujson"
      self."webob"
      self."zake"
    ];
    meta = {
      license = [ { fullName = "Apache License (2.0)"; } ];
    };
  };
  "stevedore" = super.buildPythonPackage rec {
    pname = "stevedore";
    version = "1.32.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e6/49/a35dd566626892d577e426dbe5ea424dd7fbe10645f2c1070dcba474eca9/stevedore-1.32.0-py2.py3-none-any.whl";
      sha256 = "16wwys18v1an2bpr7wwphadmpm0rihsy5zyqyzif7wmhkxsxrrx4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pbr"
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "strict-rfc3339" = super.buildPythonPackage rec {
    pname = "strict-rfc3339";
    version = "0.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/56/e4/879ef1dbd6ddea1c77c0078cd59b503368b0456bcca7d063a870ca2119d3/strict-rfc3339-0.7.tar.gz";
      sha256 = "0xqjbsn0g1h88rayh5yrpdagq60zfwrfs3yvk6rmgby3vyz1gbaw";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ { fullName = "GNU General Public License v3 (GPLv3)"; } { fullName = "GNU General Public License Version 3"; } ];
    };
  };
  "tenacity" = super.buildPythonPackage rec {
    pname = "tenacity";
    version = "6.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9a/30/4d1205370f249f6e3ff0d29f8eb3aebfb7f88bf925364a222c6abcbc383e/tenacity-6.1.0-py2.py3-none-any.whl";
      sha256 = "0fv1mn1schlm83221w904krlm68wifl9dxb1iz1wyx9qnmdvzg7p";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "tooz" = super.buildPythonPackage rec {
    pname = "tooz";
    version = "1.66.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d7/26/5b64ece3bed74739ea763ede1380253dca050b9c83cc244200be7b2c6a66/tooz-1.66.1-py2.py3-none-any.whl";
      sha256 = "182rrk9if6qy6akvjhjq2n186ghq9s5ywgl57lgdd5pl985dhn8m";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."fasteners"
      self."futurist"
      self."msgpack"
      self."oslo.serialization"
      self."oslo.utils"
      self."pbr"
      self."six"
      self."stevedore"
      self."tenacity"
      self."voluptuous"
    ];
    meta = {
      license = [ { fullName = "Apache-2"; } pkgs.lib.licenses.asl20 ];
    };
  };
  "tzlocal" = super.buildPythonPackage rec {
    pname = "tzlocal";
    version = "2.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ef/99/53bd1ac9349262f59c1c421d8fcc2559ae8a5eeffed9202684756b648d33/tzlocal-2.0.0-py2.py3-none-any.whl";
      sha256 = "0j4h0dp5f9m51hlhnrvvwr1d0h33lkc9gppfw5h4nfv319pg3j8i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pytz"
    ];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "ujson" = super.buildPythonPackage rec {
    pname = "ujson";
    version = "1.35";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/16/c4/79f3409bc710559015464e5f49b9879430d8f87498ecdc335899732e5377/ujson-1.35.tar.gz";
      sha256 = "11jz5wi7mbgqcsz52iqhpyykiaasila4lq8cmc2d54bfa3jp6q7n";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "1.25.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e1/e5/df302e8017440f111c11cc41a6b432838672f5a70aa29227bf58149dc72f/urllib3-1.25.9-py2.py3-none-any.whl";
      sha256 = "05cikmgc4phnk6aidvnhj00rvyz3159aqhs889ynfvbyp076n848";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "validate-email" = super.buildPythonPackage rec {
    pname = "validate-email";
    version = "1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/84/a0/cb53fb64b52123513d04f9b913b905f3eb6fda7264e639b4573cc715c29f/validate_email-1.3.tar.gz";
      sha256 = "1bxffaf5yz2cph8ki55vdvdypbwkvn2xr1firlcy62vqbzf1jivq";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ { fullName = "LGPL"; } ];
    };
  };
  "vine" = super.buildPythonPackage rec {
    pname = "vine";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7f/60/82c03047396126c8331ceb64da1dc52d4f1317209f32e8fe286d0c07365a/vine-1.3.0-py2.py3-none-any.whl";
      sha256 = "1bwq7yx13npsnil8wlljhvvndnfs4pp47mf8jlh6zzfiav64fjga";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "voluptuous" = super.buildPythonPackage rec {
    pname = "voluptuous";
    version = "0.11.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/24/3b/fe531688c0d9e057fccc0bc9430c0a3d4b90e0d2f015326e659c2944e328/voluptuous-0.11.7.tar.gz";
      sha256 = "0mplkcpb5d8wjf8vk195fys4y6a3wbibiyf708imw33lphfk9g1a";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "webob" = super.buildPythonPackage rec {
    pname = "webob";
    version = "1.8.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/06/e1/4acd2b4327fceb4c6446bdbca515f807ab83188526fd654940c00bcf8cc3/WebOb-1.8.5-py2.py3-none-any.whl";
      sha256 = "0az1kmhrrlmd81bma5x35bg10fsyymxql8003f6dc8vhqq1q5nrn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "wrapt" = super.buildPythonPackage rec {
    pname = "wrapt";
    version = "1.12.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/82/f7/e43cefbe88c5fd371f4cf0cf5eb3feccd07515af9fd6cf7dbf1d1793a797/wrapt-1.12.1.tar.gz";
      sha256 = "1mwpkdnqxf0yxj1a0hsnl06lf287qi5ap7309wm37x45zf0zlbxn";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "yaql" = super.buildPythonPackage rec {
    pname = "yaql";
    version = "1.1.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/77/89/cfee017cf4f2d6f5e7159bbf13fe4131c7dbf20d675b78c9928ae9aa9df8/yaql-1.1.3.tar.gz";
      sha256 = "02fj0n6919n0h0qkrb3szyk9g4s3c3x2f3gq0fn9f75nm3lxjd0i";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      self."pbr"
    ];
    propagatedBuildInputs = [
      self."Babel"
      self."pbr"
      self."ply"
      self."python-dateutil"
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "zake" = super.buildPythonPackage rec {
    pname = "zake";
    version = "0.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/58/38/2655656789f5b22e4d329ce1d4b23519732855459fc277bd718fb1ab89ce/zake-0.2.2-py2.py3-none-any.whl";
      sha256 = "0j7zykxrl5g1dy46mhyr3m0n0v684r4z3p1k6y3ari4mshr5gfl7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."kazoo"
      self."six"
    ];
    meta = {
      license = [ { fullName = "ASL 2.0"; } pkgs.lib.licenses.asl20 ];
    };
  };
  "zipp" = super.buildPythonPackage rec {
    pname = "zipp";
    version = "3.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b2/34/bfcb43cc0ba81f527bc4f40ef41ba2ff4080e047acb0586b56b3d017ace4/zipp-3.1.0-py3-none-any.whl";
      sha256 = "02rjw1wk2bcf6xpsbhga80a8kvhnf5wms19rlrzyzdy0y07madma";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
}
