# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "colorful" = super.buildPythonPackage rec {
    pname = "colorful";
    version = "0.5.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b0/8e/e386e248266952d24d73ed734c2f5513f34d9557032618c8910e605dfaf6/colorful-0.5.4-py2.py3-none-any.whl";
      sha256 = "0j0kafacz95bwb7x5q4vm5cha6y8mvxnm972lc5lrblsld94n9ld";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "docopt" = super.buildPythonPackage rec {
    pname = "docopt";
    version = "0.6.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz";
      sha256 = "14f4hn6d1j4b99svwbaji8n2zj58qicyz19mm0x6pmhb50jsics9";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "emoji" = super.buildPythonPackage rec {
    pname = "emoji";
    version = "0.5.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/40/8d/521be7f0091fe0f2ae690cc044faf43e3445e0ff33c574eae752dd7e39fa/emoji-0.5.4.tar.gz";
      sha256 = "0x61xypwswhghchp5svs084didkgfwqpq2fbiapvirff5lx2srb0";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "filetype" = super.buildPythonPackage rec {
    pname = "filetype";
    version = "1.0.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f1/ad/e1e0e85a2c2d02f634a9a400b4476f8187a634ee9d629df16f6432a6ed21/filetype-1.0.6-py2.py3-none-any.whl";
      sha256 = "0c5cwbljm17lv84wq2y7yrpjyc2aw2kknv7vr7wcrb10d32hwvgx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "gitdb" = super.buildPythonPackage rec {
    pname = "gitdb";
    version = "4.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/74/52/ca35448b56c53a079d3ffe18b1978c6e424f6d4df02404877094c89f5bfb/gitdb-4.0.4-py3-none-any.whl";
      sha256 = "0skccpfb3zhamjmcwwginz3n8l1i4vp0p6dam1x9331fj70344ds";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."smmap"
    ];
  };
  "gitpython" = super.buildPythonPackage rec {
    pname = "gitpython";
    version = "3.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/19/1a/0df85d2bddbca33665d2148173d3281b290ac054b5f50163ea735740ac7b/GitPython-3.1.1-py3-none-any.whl";
      sha256 = "0gcbay15a6gifjya1zw44hlwxk5fd9j0naqgjgjdmywy83bxmf3i";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."gitdb"
    ];
  };
  "humanize" = super.buildPythonPackage rec {
    pname = "humanize";
    version = "2.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e8/40/8a07471de13c7bb29408840da35fed591883d794e0dd1b43ccd4f4b3d436/humanize-2.4.0-py3-none-any.whl";
      sha256 = "00i04wd9ysm8bc1rz6ik1vp5ncdj845jrhndbjm7viy6pa9i5p87";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "junit-xml" = super.buildPythonPackage rec {
    pname = "junit-xml";
    version = "1.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2a/93/2d896b5fd3d79b4cadd8882c06650e66d003f465c9d12c488d92853dff78/junit_xml-1.9-py2.py3-none-any.whl";
      sha256 = "0cj73dv2pmj89dm6hyd9dw8cfmnia59162yciz97dpggbajs2p7c";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
  };
  "lxml" = super.buildPythonPackage rec {
    pname = "lxml";
    version = "4.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/39/2b/0a66d5436f237aff76b91e68b4d8c041d145ad0a2cdeefe2c42f76ba2857/lxml-4.5.0.tar.gz";
      sha256 = "0q5v7c9k09md6czyl2z0i1xq7hkn4p691gw3850ks0hdyn0cw846";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "mock" = super.buildPythonPackage rec {
    pname = "mock";
    version = "4.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cd/74/d72daf8dff5b6566db857cfd088907bb0355f5dd2914c4b3ef065c790735/mock-4.0.2-py3-none-any.whl";
      sha256 = "1q419mxii2491bjvk2n5xn66fsxqlwjmhzrhiy1j23f6jq0jr6rz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "netaddr" = super.buildPythonPackage rec {
    pname = "netaddr";
    version = "0.7.19";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ba/97/ce14451a9fd7bdb5a397abf99b24a1a6bb7a1a440b019bebd2e9a0dbec74/netaddr-0.7.19-py2.py3-none-any.whl";
      sha256 = "1jh87s49dz1xywsk7559m2km83k672gk8bn5wjcnjgqzsy5mbcsn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "parse" = super.buildPythonPackage rec {
    pname = "parse";
    version = "1.15.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f4/65/220bb4075fddb09d5b3ea2c1c1fa66c1c72be9361ec187aab50fa161e576/parse-1.15.0.tar.gz";
      sha256 = "1h4m5df5grjpaf087g8ciishz5ajl28s3140s8bngppvy71f5m56";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "parse-type" = super.buildPythonPackage rec {
    pname = "parse-type";
    version = "0.5.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1b/81/2a168b41acb57f1ea8e1e09937f585a0b9105557b13562ff8655fea81c09/parse_type-0.5.2-py2.py3-none-any.whl";
      sha256 = "17kzaxvqyv61nv4b9dd1liccdhrh8a2dvhpybn306w9j0qdlg6h8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."parse"
      self."six"
    ];
  };
  "pysingleton" = super.buildPythonPackage rec {
    pname = "pysingleton";
    version = "0.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/93/4d/0a4d66a12b129ebe512e62ddf3d935bc2b8b80cb209cdd45b4e9b0d21dfa/pysingleton-0.2.1.tar.gz";
      sha256 = "1k6vn10hvnmk7mr10h7kzs2l70f593kg8156kmq2daqbpajffxjp";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "radish-bdd" = super.buildPythonPackage rec {
    pname = "radish-bdd";
    version = "0.13.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/14/80/a5c48f42f6a6223e2f494a3a3882606aaa449babfb1a658673d24e24e1b6/radish_bdd-0.13.1-py2.py3-none-any.whl";
      sha256 = "0815s7w0lm4nm45a3bqdyhybv1qci25vz6ddxicqyiakyp6w1b9a";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."colorful"
      self."docopt"
      self."humanize"
      self."parse-type"
      self."pysingleton"
      self."tag-expressions"
      self.setuptools
    ];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.14.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl";
      sha256 = "0v2bfai6xiqkl06hy7996wkbali2p5vxznfnygkr7xyqakid4g4g";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "smmap" = super.buildPythonPackage rec {
    pname = "smmap";
    version = "3.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/27/b1/e379cfb7c07bbf8faee29c4a1a2469dbea525f047c2b454c4afdefa20a30/smmap-3.0.2-py2.py3-none-any.whl";
      sha256 = "1hgbigni2k6qdsz2cp1l2fwkvigfzg1nyfz9ryqc5lh8wyrpisjj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tag-expressions" = super.buildPythonPackage rec {
    pname = "tag-expressions";
    version = "1.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/80/9c/d7f83ffcb34a267b03a742e25239d05fdf151cb749035a107ceec2432398/tag_expressions-1.1.0-py3-none-any.whl";
      sha256 = "0lbylfk6pqi59g2kvynsp27c1x4nj4dmidaaqn77fmjv94bbdlj5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "terraform-compliance" = super.buildPythonPackage rec {
    pname = "terraform-compliance";
    version = "1.1.16";
    src = pkgs.fetchFromGitHub {
      owner = "eerkunt";
      repo = "terraform-compliance";
      rev = "20fa75221fcce0ef42c919b9b799411c447e3b52";
      sha256 = "036n3d1j110vhybw8nz4f0c0n9v7kx3wnvl6ncfrp8fwsyk51k9a";
    };

    patches = [
      ./fix_data.patch
    ];

    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."colorful"
      self."emoji"
      self."filetype"
      self."gitpython"
      self."junit-xml"
      self."lxml"
      self."mock"
      self."netaddr"
      self."radish-bdd"
    ];
  };
}
