dist: bionic
language: generic
before_install:
  - curl https://nixos.org/nix/install | sh
  - sudo mkdir -p /etc/nix && echo 'sandbox = true' | sudo tee /etc/nix/nix.conf
  - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
  - . /home/travis/.nix-profile/etc/profile.d/nix.sh
  - nix-shell --run ./run.sh

before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f default.nix buildInputs

cache:
  directories:
  - $HOME/nix.store
