dist: bionic
language: generic
before_install:
  - sudo apt-get update
  - sudo apt-get -y --force-yes install linux-headers-`uname -r` software-properties-common
  - wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo add-apt-repository "deb http://download.virtualbox.org/virtualbox/debian bionic contrib"
  - sudo apt-get update
  - sudo apt-get -y install -q virtualbox-6.0
  - curl https://nixos.org/nix/install | sh
  - sudo mkdir -p /etc/nix && echo 'sandbox = true' | sudo tee /etc/nix/nix.conf
  - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
  - . /home/travis/.nix-profile/etc/profile.d/nix.sh
  - travis_wait 60 nix-shell --run ./run.sh

before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f shell.nix buildInputs

cache:
  directories:
  - $HOME/nix.store
