dist: bionic
language: generic
before_install:
  - sudo apt-get update
  - sudo apt-get -y --force-yes install linux-headers-`uname -r` software-properties-common
  - wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo add-apt-repository "deb http://download.virtualbox.org/virtualbox/debian bionic contrib"
  - sudo apt-get update
  - sudo apt-get -y install -q virtualbox-6.0
  - curl https://nixos.org/nix/install | sh
  - sudo mkdir -p /etc/nix && echo 'sandbox = true' | sudo tee /etc/nix/nix.conf
  - echo "trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= laptop-dotfiles.cachix.org-1:Okurdv1/SRJkXNODJsAi/K6FZLDmhr4gMSwV9XiWw+g= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo "substituters = https://cache.nixos.org https://laptop-dotfiles.cachix.org https://cache.nixos.org/" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
  - . /home/travis/.nix-profile/etc/profile.d/nix.sh
  - travis_wait 80 nix-shell --run ./run.sh
