dist: bionic
language: generic
before_install:
  - curl https://nixos.org/nix/install | sh
  - . /home/travis/.nix-profile/etc/profile.d/nix.sh
  - nix-shell --run ./run.sh

before_script:
  - sudo mkdir /etc/nix && echo 'sandbox = true' | sudo tee /etc/nix/nix.conf
