# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "argparse" = super.buildPythonPackage rec {
    pname = "argparse";
    version = "1.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl";
      sha256 = "0533cr5w14da8wdb2q4py6aizvbvsdbk3sj7m1jx9lwznvnlf5n3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.psfl ];
    };
  };
  "bcrypt" = super.buildPythonPackage rec {
    pname = "bcrypt";
    version = "3.1.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fa/aa/025a3ab62469b5167bc397837c9ffc486c42a97ef12ceaa6699d8f5a5416/bcrypt-3.1.7.tar.gz";
      sha256 = "0hhywhxx301cxivgxrpslrangbfpccc8y83qbwn1f57cab3nj00b";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [
      self."setuptools"
      self."wheel"
      self."cffi"
    ];
    propagatedBuildInputs = [
      self."cffi"
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "cffi" = super.buildPythonPackage rec {
    pname = "cffi";
    version = "1.14.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/54/3324b0c46340c31b909fcec598696aaec7ddc8c18a63f2db352562d3354c/cffi-1.14.0.tar.gz";
      sha256 = "1dn279gw5ql8i5n3s5v4rnv96rhhjjfn7xq729qbl5bs2954yf1d";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pycparser"
    ];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "dnspython" = super.buildPythonPackage rec {
    pname = "dnspython";
    version = "1.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ec/d3/3aa0e7213ef72b8585747aa0e271a9523e713813b9a20177ebe1e939deb0/dnspython-1.16.0-py2.py3-none-any.whl";
      sha256 = "0bb3y7j6wdly1pl41myk71wvl6ni95dr1i2ndsl4sbwni8l2377n";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ { fullName = "Freeware"; } { fullName = "BSD-like"; } ];
    };
  };
  "eventlet" = super.buildPythonPackage rec {
    pname = "eventlet";
    version = "0.25.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ef/01/83454d11bac9015f34e93cf11efcae169390ddf2df97cb73ca86de6465ed/eventlet-0.25.1-py2.py3-none-any.whl";
      sha256 = "1cg6plbj43pw0175r23jlqn4xxi80lg89qhdhsjc3b9p17c1r2v5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."dnspython"
      self."greenlet"
      self."monotonic"
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "greenlet" = super.buildPythonPackage rec {
    pname = "greenlet";
    version = "0.4.15";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f8/e8/b30ae23b45f69aa3f024b46064c0ac8e5fcb4f22ace0dca8d6f9c8bbe5e7/greenlet-0.4.15.tar.gz";
      sha256 = "1g4g1wwc472ds89zmqlpyan3fbnzpa8qm48z3z1y6mlk44z485ll";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "gunicorn" = super.buildPythonPackage rec {
    pname = "gunicorn";
    version = "19.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8c/da/b8dd8deb741bff556db53902d4706774c8e1e67265f69528c14c003644e6/gunicorn-19.9.0-py2.py3-none-any.whl";
      sha256 = "0w947i3p0b7y1qxkpfj573s6lvf7r52rynayvyjkcyqmni00p3ma";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "monotonic" = super.buildPythonPackage rec {
    pname = "monotonic";
    version = "1.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ac/aa/063eca6a416f397bd99552c534c6d11d57f58f2e94c14780f3bbf818c4cf/monotonic-1.5-py2.py3-none-any.whl";
      sha256 = "1iqc2k8nmk6bkqisg3xvca4hh20rl9ajcskws35k6bjkh7rr2ajm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ { fullName = "Apache"; } pkgs.lib.licenses.asl20 ];
    };
  };
  "netaddr" = super.buildPythonPackage rec {
    pname = "netaddr";
    version = "0.7.19";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ba/97/ce14451a9fd7bdb5a397abf99b24a1a6bb7a1a440b019bebd2e9a0dbec74/netaddr-0.7.19-py2.py3-none-any.whl";
      sha256 = "1jh87s49dz1xywsk7559m2km83k672gk8bn5wjcnjgqzsy5mbcsn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal pkgs.lib.licenses.mit ];
    };
  };
  "oslo.config" = super.buildPythonPackage rec {
    pname = "oslo.config";
    version = "1.12.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c7/82/263fa79866098034917be0def7ab4979480e6f429732cd6cd9f4e0405ec5/oslo.config-1.12.1-py2.py3-none-any.whl";
      sha256 = "0jypai43x8ygjf8xlcwh39gqmr8cpbmh97q110102pcmrq8isl6l";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."argparse"
      self."netaddr"
      self."six"
      self."stevedore"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "passlib" = super.buildPythonPackage rec {
    pname = "passlib";
    version = "1.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ee/a7/d6d238d927df355d4e4e000670342ca4705a72f0bf694027cf67d9bcf5af/passlib-1.7.1-py2.py3-none-any.whl";
      sha256 = "106jd4pq34prjxsl7ds7h6vqawkn9hy9dsdvvfvcccps13m6llj3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "pbr" = super.buildPythonPackage rec {
    pname = "pbr";
    version = "5.4.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/96/ba/aa953a11ec014b23df057ecdbc922fdb40ca8463466b1193f3367d2711a6/pbr-5.4.5-py2.py3-none-any.whl";
      sha256 = "1s13pashfg3bmqach8hkzdwwpv28yrqjyqfyn0j2y34f7zi714ap";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "pycparser" = super.buildPythonPackage rec {
    pname = "pycparser";
    version = "2.20";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl";
      sha256 = "01apwc8fj6qh7lr01yxmns475rfhz07gccr8220ws3wgcwiav0km";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "pymongo" = super.buildPythonPackage rec {
    pname = "pymongo";
    version = "3.10.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5d/86/bfcec2a1c99e52344530e581a89871738bdcbf2c8f2ba681ad891e0980f1/pymongo-3.10.0.tar.gz";
      sha256 = "0z1h7yzh9h1cxq7zw4z6ryj2hi51bbfgpsfshipam9ky8bz7jf64";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.13.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl";
      sha256 = "1zckxq1k0yyy65hzm3hmlvmiqhpvibkfm797nsfjl22lw917s6qz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "st2-auth-backend-flat-file" = super.buildPythonPackage rec {
    pname = "st2-auth-backend-flat-file";
    version = "0.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a8/36/457e992088c296b295eb3fe8495a240e6233ce0d1dc47d72a977c319766a/st2_auth_backend_flat_file-0.1.0-py3-none-any.whl";
      sha256 = "13z7j81hfrwk4ybz3nc2a8n8kaahkg6wayzrmgwbzjrbjp538qnp";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."passlib"
    ];
    meta = {
      license = [ { fullName = "Apache License (2.0)"; } pkgs.lib.licenses.asl20 ];
    };
  };
  "st2auth" = super.buildPythonPackage rec {
    pname = "st2auth";
    version = "3.2.dev0";
    src = "${fetchgit {
        url = "https://github.com/stackstorm/st2.git";
        rev = "5bd298ac3ded9cad4eda0886b4d3197753edd0d3";
        sha256 = "0gl3pzh082d5hyacyqd6q63lwzvj97p7g4wlckdc8wvfjpchlfwq";
      }
    }/st2auth";
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."bcrypt"
      self."eventlet"
      self."gunicorn"
      self."oslo.config"
      self."passlib"
      self."pymongo"
      self."six"
      self."st2-auth-backend-flat-file"
      self."stevedore"
    ];
    meta = {
      license = [ { fullName = "Apache License (2.0)"; } ];
    };
  };
  "stevedore" = super.buildPythonPackage rec {
    pname = "stevedore";
    version = "1.30.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c6/dc/6ee92bccfe3c0448786b30b693e6060d62ec8c4a3ec9a287bac1c1a8d8c9/stevedore-1.30.1-py2.py3-none-any.whl";
      sha256 = "18ifjdgjnqr24dnpyamdxx9fbxxpz431z9kx10yga9kxm08fc73x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pbr"
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
}
