# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "argcomplete" = super.buildPythonPackage rec {
    pname = "argcomplete";
    version = "1.11.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/82/7d/455e149c28c320044cb763c23af375bd77d52baca041f611f5c2b4865cf4/argcomplete-1.11.1-py2.py3-none-any.whl";
      sha256 = "1mrpxxchlxwca05r3hl8wn08b5bdigkn65r4vdryswxrrcgxs2w9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."importlib-metadata"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2020.4.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/57/2b/26e37a4b034800c960a00c4e1b3d9ca5d7014e983e6e729e33ea2f36426c/certifi-2020.4.5.1-py2.py3-none-any.whl";
      sha256 = "016kmf145apmfkrpxwd7434hcjchypy6djbwhi03qqvmijcpm60x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mpl20 { fullName = "Mozilla Public License 2.0 (MPL 2.0)"; } ];
    };
  };
  "cffi" = super.buildPythonPackage rec {
    pname = "cffi";
    version = "1.14.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/05/54/3324b0c46340c31b909fcec598696aaec7ddc8c18a63f2db352562d3354c/cffi-1.14.0.tar.gz";
      sha256 = "1dn279gw5ql8i5n3s5v4rnv96rhhjjfn7xq729qbl5bs2954yf1d";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pycparser"
    ];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "chardet" = super.buildPythonPackage rec {
    pname = "chardet";
    version = "3.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl";
      sha256 = "14b621614q2lw7ik2igdv4qdbblqgdsiglgl5fhf1l5fmvy3ycpw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ { fullName = "LGPL"; } { fullName = "GNU Library or Lesser General Public License (LGPL)"; } ];
    };
  };
  "cryptography" = super.buildPythonPackage rec {
    pname = "cryptography";
    version = "2.8";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/be/60/da377e1bed002716fb2d5d1d1cab720f298cb33ecff7bf7adea72788e4e4/cryptography-2.8.tar.gz";
      sha256 = "0l8nhw14npknncxdnp7n4hpmjyscly6g7fbivyxkjwvlv071zniw";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cffi"
      self."six"
    ];
    meta = {
      license = [ { fullName = "BSD or Apache License, Version 2.0"; } pkgs.lib.licenses.bsdOriginal pkgs.lib.licenses.asl20 ];
    };
  };
  "decorator" = super.buildPythonPackage rec {
    pname = "decorator";
    version = "4.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl";
      sha256 = "0q7p11gj5g158gb1igy9cna5ppxf03zkrm2gpr4acjycl3159yj1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ { fullName = "new BSD License"; } pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "2.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl";
      sha256 = "1yk5hf2jkw1237b508mxmcdm8zqhfh26fr6rpwyxd968x8fa4s50";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ { fullName = "BSD-like"; } pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "importlib-metadata" = super.buildPythonPackage rec {
    pname = "importlib-metadata";
    version = "1.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ad/e4/891bfcaf868ccabc619942f27940c77a8a4b45fd8367098955bb7e152fb1/importlib_metadata-1.6.0-py2.py3-none-any.whl";
      sha256 = "03yr2r83p7m0fvwv6py3v7fcrbbfgb4vsj6zy63wa30fm6x8qs1a";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."zipp"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "jsonpath-rw" = super.buildPythonPackage rec {
    pname = "jsonpath-rw";
    version = "1.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/71/7c/45001b1f19af8c4478489fbae4fc657b21c4c669d7a5a036a86882581d85/jsonpath-rw-1.4.0.tar.gz";
      sha256 = "1v7vqkx136y8xm2xx05ajqp1m0x4qy72dl83c4zi3bj53hl73i05";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."decorator"
      self."ply"
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "jsonschema" = super.buildPythonPackage rec {
    pname = "jsonschema";
    version = "2.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl";
      sha256 = "024sfr3bjikmsf085ignkdgi5lg7rah2ajal9192m5rwsfmnh3h0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "more-itertools" = super.buildPythonPackage rec {
    pname = "more-itertools";
    version = "5.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a4/a6/42f17d065bda1fac255db13afc94c93dbfb64393eae37c749b4cb0752fc7/more_itertools-5.0.0-py3-none-any.whl";
      sha256 = "1fahxq9f4dhjiy8p9v806sb7ky653gxg8gqia8wx6myb3jp7qypy";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "ply" = super.buildPythonPackage rec {
    pname = "ply";
    version = "3.11";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl";
      sha256 = "1kh7m0i2ghjhrbzi6a28yw3rcnzy5r2i4srls4pvspmna21rnvq9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "prettytable" = super.buildPythonPackage rec {
    pname = "prettytable";
    version = "0.7.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ef/30/4b0746848746ed5941f052479e7c23d2b56d174b82f4fd34a25e389831f5/prettytable-0.7.2.tar.bz2";
      sha256 = "0diwsicwmiq2cpzpxri7cyl5fmsvicafw6nfqf6p6p322dji2g45";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ { fullName = "BSD (3 clause)"; } pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "prompt-toolkit" = super.buildPythonPackage rec {
    pname = "prompt-toolkit";
    version = "1.0.15";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/04/d1/c6616dd03701e7e2073f06d5c3b41b012256e42b72561f16a7bd86dd7b43/prompt_toolkit-1.0.15-py3-none-any.whl";
      sha256 = "10f3pjgv5gmx8h9mlk5kii9sklx8v73rqddv7v2rkcyc1ri55y8x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
      self."wcwidth"
    ];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "pyOpenSSL" = super.buildPythonPackage rec {
    pname = "pyOpenSSL";
    version = "19.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9e/de/f8342b68fa9e981d348039954657bdf681b2ab93de27443be51865ffa310/pyOpenSSL-19.1.0-py2.py3-none-any.whl";
      sha256 = "011m0q162n8xw4nasw191sq6m5ki43m58bqv5z78w2vjbab80632";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cryptography"
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "pycparser" = super.buildPythonPackage rec {
    pname = "pycparser";
    version = "2.20";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl";
      sha256 = "01apwc8fj6qh7lr01yxmns475rfhz07gccr8220ws3wgcwiav0km";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "python-dateutil" = super.buildPythonPackage rec {
    pname = "python-dateutil";
    version = "2.8.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl";
      sha256 = "1yzj7m4h5babisvqac674xx82a8gd7ynxqhm2rwj7mpf9b3q8rby";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
    meta = {
      license = [ { fullName = "Dual License"; } pkgs.lib.licenses.bsdOriginal pkgs.lib.licenses.asl20 ];
    };
  };
  "python-editor" = super.buildPythonPackage rec {
    pname = "python-editor";
    version = "1.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c6/d3/201fc3abe391bbae6606e6f1d598c15d367033332bd54352b12f35513717/python_editor-1.0.4-py3-none-any.whl";
      sha256 = "0z9nr2npc0ghk0jh436qirhk082vq9fjs9g17r6a2lmdm1hfixhv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ { fullName = "Apache"; } pkgs.lib.licenses.asl20 ];
    };
  };
  "pytz" = super.buildPythonPackage rec {
    pname = "pytz";
    version = "2019.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl";
      sha256 = "1nnz65fqvydrwpg4y7hywgdinh10knndqkk0ak6065kjdgipjf1h";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "pyyaml" = super.buildPythonPackage rec {
    pname = "pyyaml";
    version = "5.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e3/e8/b3212641ee2718d556df0f23f78de8303f068fe29cdaa7a91018849582fe/PyYAML-5.1.2.tar.gz";
      sha256 = "1r5faspz73477hlbjgilw05xsms0glmsa371yqdd26znqsvg1b81";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.23.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl";
      sha256 = "1vizszbz6mdn0fmb1i75d0n5w3jn5f4f968xmyv08ad8pwv916a3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."chardet"
      self."cryptography"
      self."idna"
      self."pyOpenSSL"
      self."urllib3"
    ];
    meta = {
      license = [ pkgs.lib.licenses.asl20 ];
    };
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.13.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl";
      sha256 = "1zckxq1k0yyy65hzm3hmlvmiqhpvibkfm797nsfjl22lw917s6qz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "sseclient-py" = super.buildPythonPackage rec {
    pname = "sseclient-py";
    version = "1.7";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6a/89/200c59842a7ce06c47d6cf2ab7598110c39909f5dc30c633b9a049acc262/sseclient_py-1.7-py2.py3-none-any.whl";
      sha256 = "0669nxqbrkyl37yq32i02v0scv7gh54616jrfq9fginaz2hrb6nv";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ { fullName = "Apache Software License v2"; } ];
    };
  };
  "st2client" = super.buildPythonPackage rec {
    pname = "st2client";
    version = "3.2.dev0";
    src = "${fetchgit {
        url = "https://github.com/stackstorm/st2.git";
        rev = "5bd298ac3ded9cad4eda0886b4d3197753edd0d3";
        sha256 = "0gl3pzh082d5hyacyqd6q63lwzvj97p7g4wlckdc8wvfjpchlfwq";
      }
    }/st2client";
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."argcomplete"
      self."cryptography"
      self."jsonpath-rw"
      self."jsonschema"
      self."more-itertools"
      self."prettytable"
      self."prompt-toolkit"
      self."python-dateutil"
      self."python-editor"
      self."pytz"
      self."pyyaml"
      self."requests"
      self."six"
      self."sseclient-py"
      self."zipp"
    ];
    meta = {
      license = [ { fullName = "Apache License (2.0)"; } pkgs.lib.licenses.asl20 ];
    };
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "1.25.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e1/e5/df302e8017440f111c11cc41a6b432838672f5a70aa29227bf58149dc72f/urllib3-1.25.9-py2.py3-none-any.whl";
      sha256 = "05cikmgc4phnk6aidvnhj00rvyz3159aqhs889ynfvbyp076n848";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "wcwidth" = super.buildPythonPackage rec {
    pname = "wcwidth";
    version = "0.1.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f6/d5/1ecdac957e3ea12c1b319fcdee8b6917ffaff8b4644d673c4d72d2f20b49/wcwidth-0.1.9-py2.py3-none-any.whl";
      sha256 = "1qdvs6cnb3c8p28lfkzfcn6qvcwwszff2b02cx0a02f0nf323zna";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
  "zipp" = super.buildPythonPackage rec {
    pname = "zipp";
    version = "1.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f4/50/cc72c5bcd48f6e98219fc4a88a5227e9e28b81637a99c49feba1d51f4d50/zipp-1.0.0-py2.py3-none-any.whl";
      sha256 = "0mknwfyqc1l1wzcfx903qlri4vkvnh5sby0dfbc4nryidgq7inld";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."more-itertools"
    ];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
}
