# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "nixos"

  config.vm.hostname = "nixos"


  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  
    vb.memory = "13000"

    vb.customize ["modifyvm", :id, "--accelerate3d", "on", "--accelerate2dvideo", "on"]
  end

  config.vm.provision :nixos,
    run: 'always',
    path: "nixos/configuration.nix",
    include: true,
    verbose: true


end
