# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "juliosueiras/nixbox"

  config.vm.hostname = "nixos"

  config.vm.synced_folder "#{ENV["HOME"]}/projects", "/projects"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  
    vb.memory = "13000"

    #vb.cpus = 2

    vb.customize ["modifyvm", :id, "--graphicscontroller" ,"vboxsvga","--accelerate2dvideo", "on", "--accelerate3d", "on", "--vram", "256", "--usb", "on"]



  end

  config.vm.provision :nixos,
    run: 'always',
    path: "nixos/configuration.nix",
    include: true,
    verbose: true


end
